import uuid from 'uuid/v1';


export default [
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7702 NOP',
    maintenanceType: 'Engine oil, Filter oil',
    next: 230121,
    cost: 'IDR 2.000.000',
    notes: 'Oli Gardan harus segera ganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7341 CSO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 239100,
    cost: 'IDR 1.700.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7992 BHU',
    maintenanceType: 'Engine oil, Filter oil',
    next: 120100,
    cost: 'IDR 1.500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'TOYOTA DYNA',
    licensePlate:'B 7921 KAI',
    maintenanceType: 'Engine oil, Filter oil',
    next: 190120,
    cost: 'IDR 1.300.000',
    notes: 'Busi harus segera ganti',
  },
 
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7621 SAO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 229000,
    cost: 'IDR 1.200.000',
    notes: 'Kampas rem',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7621 SAO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 109899,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, FUSO',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 180200,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 110299,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 129011,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 187000,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
];
