import uuid from 'uuid/v1';


export default [
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 2.000.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 1.000.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 1.000.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 1.000.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
  {
    id: uuid(),
    VehicleName: 'MITSUBISHI, CANTER 120 PS',
    licensePlate:'B 7120 TEO',
    maintenanceType: 'Engine oil, Filter oil',
    next: 202001,
    cost: 'IDR 500.000',
    notes: 'Ban harus segera diganti',
  },
];
